---
- name: InstructLab Setup for RPM based systems
  hosts: localhost
  become: yes
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    instructlab_repo: "https://github.com/actual-org/instructlab.git"
    install_dir: "/opt/instructlab"
    install_dir_owner: "root"
    install_dir_group: "root"
    install_dir_mode: '0755'
    required_packages:
      - git
      - python3
      - python3-pip
      - docker
      - additional-package
    instructlab_version: "v1.0.0"
    pip_requirements: "/opt/instructlab/requirements.txt"
    pip_executable: "pip3"
    install_script: "/opt/instructlab/install.sh"
    install_script_exists: "/opt/instructlab/install.sh"
    verify_command: "/opt/instructlab/instructlab --version"
  roles:
    - role: ilabsetup