---
- name: InstructLab Setup for RPM based systems
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Install, configure InstructLab
      import_role:
        name: InstructLab_rpmBased