---
- name: Ensure required packages are installed
  yum:
    name: "{{ required_packages }}"
    state: present

- name: Ensure Docker service is running (if required)
  service:
    name: docker
    state: started
    enabled: yes
  when: "'docker' in ansible_facts.packages"

- name: Create installation directory
  file:
    path: "{{ install_dir }}"
    state: directory
    owner: "{{ install_dir_owner }}"
    group: "{{ install_dir_group }}"
    mode: "{{ install_dir_mode }}"

- name: Clone InstructLab repository
  git:
    repo: "{{ instructlab_repo }}"
    dest: "{{ install_dir }}"
    version: "{{ instructlab_version }}"
    clone: yes
    update: yes

- name: Install Python dependencies (if required)
  pip:
    requirements: "{{ pip_requirements }}"
    executable: "{{ pip_executable }}"

- name: Run InstructLab installation script (if provided)
  command: "{{ install_script }}"
  args:
    chdir: "{{ install_dir }}"
  when: "install_script_exists.stat.exists"

- name: Verify InstructLab installation
  command: "{{ verify_command }}"
  register: instructlab_version
  changed_when: false

- name: Display InstructLab version
  debug:
    msg: "InstructLab version: {{ instructlab_version.stdout }}"